### PR TITLE
upgrade tensorflow-addons to 0.10

### PR DESCRIPTION
**Pull request by amitport**
needed for pip install with python 3.8

(so apparently dm-tree@0.1.1 still does not support 3.8, so in any case this is would not allow tff to be used out of the box with python 3.8)

### CODE REVIEW

**Comment by michaelreneer** [comment]
@amitport Thanks for the change, I think this would be helpful. I added comment to point to two locations that also need to be updated. LMK, if I can help explain more.

**Comment by amitport** [comment]
hi @michaelreneer, the requirements.txt and the docker file are using `tfa-nightly` (and `tf-nightly`), so no need to upgrade (possibly would be wise to use stable versions, but not a part of this PR)

**Comment by Buddha33** [comment]
Norm

**Comment by amitport** [comment]
The exact same change was committed by @michaelreneer in a different commit https://github.com/tensorflow/federated/commit/3af6ea398990ec49da35dd0aa171269b47ed5eea#diff-d64732508af3c7c5511760f5bd6a1028

It would have been nice to at least get a response here

**Pull request closed without merging**
