### PR TITLE
Docs should indicate python 3.10 is required; Fix #3109

### LINKED ISSUE #3109: import tensorflow_federated gives TypeError: Callable[[arg, ...], result]: each arg must be a type. Got Ellipsis
**Describe the bug**
Running `import tensorflow_federated` results in the following error

```
In [1]: import tensorflow_federated as tff
2022-07-25 22:26:48.873075: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:
2022-07-25 22:26:48.873130: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-961ae1555cfa> in <module>
----> 1 import tensorflow_federated as tff

~/.local/lib/python3.7/site-packages/tensorflow_federated/__init__.py in <module>
     20 from tensorflow_federated.python import aggregators
     21 from tensorflow_federated.python import analytics
---> 22 from tensorflow_federated.python import learning
     23 from tensorflow_federated.python import program
     24 from tensorflow_federated.python import simulation

~/.local/lib/python3.7/site-packages/tensorflow_federated/python/learning/__init__.py in <module>
     36 """
     37 
---> 38 from tensorflow_federated.python.learning import algorithms
     39 from tensorflow_federated.python.learning import framework
     40 from tensorflow_federated.python.learning import metrics

~/.local/lib/python3.7/site-packages/tensorflow_federated/python/learning/algorithms/__init__.py in <module>
     14 """Libraries providing implementations of federated learning algorithms."""
     15 
---> 16 from tensorflow_federated.python.learning.algorithms.fed_avg import build_unweighted_fed_avg
     17 from tensorflow_federated.python.learning.algorithms.fed_avg import build_weighted_fed_avg
     18 from tensorflow_federated.python.learning.algorithms.fed_avg_with_optimizer_schedule import build_weighted_fed_avg_with_optimizer_schedule

~/.local/lib/python3.7/site-packages/tensorflow_federated/python/learning/algorithms/fed_avg.py in <module>
     48 from tensorflow_federated.python.learning import model as model_lib
     49 from tensorflow_federated.python.learning import model_utils
---> 50 from tensorflow_federated.python.learning.metrics import aggregator as metric_aggregator
     51 from tensorflow_federated.python.learning.models import functional
     52 from tensorflow_federated.python.learning.optimizers import optimizer as optimizer_base

~/.local/lib/python3.7/site-packages/tensorflow_federated/python/learning/metrics/__init__.py in <module>
     14 """Libraries for working with metrics in federated learning algorithms."""
     15 
---> 16 from tensorflow_federated.python.learning.metrics.aggregator import create_default_secure_sum_quantization_ranges
     17 from tensorflow_federated.python.learning.metrics.aggregator import secure_sum_then_finalize
     18 from tensorflow_federated.python.learning.metrics.aggregator import sum_then_finalize

~/.local/lib/python3.7/site-packages/tensorflow_federated/python/learning/metrics/aggregator.py in <module>
     38 from tensorflow_federated.python.core.impl.types import type_conversions
     39 from tensorflow_federated.python.learning import model as model_lib
---> 40 from tensorflow_federated.python.learning.models import functional
     41 
     42 

~/.local/lib/python3.7/site-packages/tensorflow_federated/python/learning/models/__init__.py in <module>
     14 """Libraries for working with models in federated learning algorithms."""
     15 
---> 16 from tensorflow_federated.python.learning.models.functional import functional_model_from_keras
     17 from tensorflow_federated.python.learning.models.functional import FunctionalModel
     18 from tensorflow_federated.python.learning.models.functional import model_from_functional

~/.local/lib/python3.7/site-packages/tensorflow_federated/python/learning/models/functional.py in <module>
     37 from tensorflow_federated.python.learning import model as model_lib
     38 from tensorflow_federated.python.learning.metrics import finalizer
---> 39 from tensorflow_federated.python.learning.metrics import keras_utils
     40 from tensorflow_federated.python.tensorflow_libs import variable_utils
     41 

~/.local/lib/python3.7/site-packages/tensorflow_federated/python/learning/metrics/keras_utils.py in <module>
     38     metrics_constructor: Union[MetricConstructor, MetricsConstructor,
     39                                MetricConstructors]
---> 40 ) -> Tuple[Callable[[], StateVar], Callable[[StateVar, ...], StateVar],
     41            Callable[[StateVar], Any]]:
     42   """Turn a Keras metric construction method into a tuple of pure functions.

/opt/conda/lib/python3.7/typing.py in __getitem__(self, params)
    761                                 f" Got {args}")
    762             params = (tuple(args), result)
--> 763         return self.__getitem_inner__(params)
    764 
    765     @_tp_cache

/opt/conda/lib/python3.7/typing.py in inner(*args, **kwds)
    252         except TypeError:
    253             pass  # All real errors (not unhashable args) are raised below.
--> 254         return func(*args, **kwds)
    255     return inner
    256 

/opt/conda/lib/python3.7/typing.py in __getitem_inner__(self, params)
    784                 return self.copy_with((_TypingEllipsis, result))
    785             msg = "Callable[[arg, ...], result]: each arg must be a type."
--> 786             args = tuple(_type_check(arg, msg) for arg in args)
    787             params = args + (result,)
    788             return self.copy_with(params)

/opt/conda/lib/python3.7/typing.py in <genexpr>(.0)
    784                 return self.copy_with((_TypingEllipsis, result))
    785             msg = "Callable[[arg, ...], result]: each arg must be a type."
--> 786             args = tuple(_type_check(arg, msg) for arg in args)
    787             params = args + (result,)
    788             return self.copy_with(params)

/opt/conda/lib/python3.7/typing.py in _type_check(arg, msg, is_argument)
    140         return arg
    141     if not callable(arg):
--> 142         raise TypeError(f"{msg} Got {arg!r:.100}.")
    143     return arg
    144 

TypeError: Callable[[arg, ...], result]: each arg must be a type. Got Ellipsis.
```

**Environment (please complete the following information):**

I'm running inside the GCR deeplearning container
gcr.io/deeplearning-platform-release/base-cpu

I've installed TensorFlow and TensorFlow federated by running

```
pip install --upgrade --user tensorflow-federated
```

* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu - 20.04
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
tensorflow==2.9.1
tensorflow-federated==0.30.0

* Python version:
3.7.12

* Bazel version (if building from source):
Not applicable

* CUDA/cuDNN version:
Not applicable
* What TensorFlow Federated execution stack are you using?

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Expected behavior**

I expect it to import without any error.

**Additional context**

It looks like this code is relatively new:
https://github.com/tensorflow/federated/commits/main/tensorflow_federated/python/learning/metrics/keras_utils.py

Is the code using features that require a newer version of Python?

cc @ZacharyGarrett

### PR DESCRIPTION
**Pull request by jlewi**
* tensorflow/federated#3109 indicates that Python 3.10 is required
  to avoid various import errors.

* Update the documentation to indicate this.

* https://github.com/tensorflow/federated/issues/3109

### CODE REVIEW

**Comment by hardik-vala** [comment]
I was able to import tff and use it problem-free with Python 3.9,

```
$ python3 --version
Python 3.9.12

$ python3 -c "import tensorflow_federated as tff ; print(tff.federated_computation(lambda: 'Hello, World!')())"
b'Hello, World!'
```

**Comment by jlewi** [comment]
@hardik-vala Interesting. Come to think of it; the docker images
https://github.com/tensorflow/federated/blob/main/tensorflow_federated/tools/runtime/container/Dockerfile

are also using Python 3.9.12.  And seems to work.

So maybe the minimum is 3.9.Y for some Y?

Offhand I unfortunately don't know which version of 3.9 I was using in 
https://github.com/tensorflow/federated/issues/3109#issuecomment-1200328141

Is it worth updating the docs to point out that it has been tested with 3.9.12 ?

**Comment by jlewi** [comment]
Looks like the code for the exception is python 3.9.0
https://github.com/python/cpython/blob/9cf6752276e6fcfd0c23fdb064ad27f448aaaf75/Lib/typing.py#L826

Looks like it is fixed in 3.9.2
https://github.com/python/cpython/blob/v3.9.2/Lib/typing.py

**Comment by jlewi** [comment]
@hardik-vala Updated the docs to indicate 3.9.2 is the minimum.

**Comment by michaelreneer** [comment]
@jlewi 

We are not currently compatible with Python 3.10 due to some dependency issues that I expect to have resolved soon.

Additionally, we use to document the Python and TF compatibility in the README, but this became something that we needed to maintain in multiple places. Today the Python compatibility is:
* defined in the [setup.py](https://github.com/tensorflow/federated/blob/main/tensorflow_federated/tools/python_package/setup.py)
* documented on https://pypi.org/project/tensorflow-federated/
* I thought it was enforced by PIP, but I was mistaken and the classifiers are not taken into account. I am in the process of submitting a change to add https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires to our configuration. This should make it more obvious when looking at the setup.py what the required Python version is and it should make it more obvious when you invoke `pip install` that the version of Python you have is not compatible with the version of TFF you are trying to install.

As a result I would like to avoid adding additional documentation that needs to be updated as the Python compatibility changes. However, I appreciate you brining up this issue because I thought that pip was enforcing this and it's clearly not.

**Comment by jlewi** [comment]
@michaelreneer Thanks for the detailed explanation.

**Pull request closed without merging**
